#+TITLE: Matt Gauger's Emacs configuration
#+OPTIONS: toc:4 h:4

* Configuration
** About this file
<<babel-init>>

Inspired by [[https://github.com/sachac/.emacs.d/blob/gh-pages/Sacha.org][Sacha Chua's Emacs configuration]] which demonstrates how to use org-babel to create a literate programming Emacs config.

** Personal information
#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Matt Gauger"
        user-mail-address "matt.gauger@gmail.com")
#+END_SRC

** Emacs initialization

*** Add package sources

#+BEGIN_SRC emacs-lisp
  (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)

  (unless (assoc-default "melpa" package-archives)
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t))

  (when (not package-archive-contents)
    (package-refresh-contents))
#+END_SRC

*** Load secrets

If I had any, this is where they'd live:

#+BEGIN_SRC emacs-lisp
(load "~/.emacs.secrets" t)
#+END_SRC

** General configuration

*** Backups

I used the approach my old =.emacs= config file used in setting up backup files:

Do not save autosave/swap files in current directory. Save all tempfiles in $TMPDIR/emacs$UID/ instead:

#+BEGIN_SRC emacs-lisp
(defconst emacs-tmp-dir (format "%s/%s%s/" temporary-file-directory "emacs" (user-uid)))

(setq backup-directory-alist
      `((".*" . ,emacs-tmp-dir)))
(setq auto-save-file-name-transforms
      `((".*" ,emacs-tmp-dir t)))
(setq auto-save-list-file-prefix
      emacs-tmp-dir)
#+END_SRC

Disk space is cheap. Save lots.

#+BEGIN_SRC emacs-lisp
(setq delete-old-versions -1)
(setq version-control t)
(setq vc-make-backup-files t)
#+END_SRC


*** History

From http://pages.sachachua.com/.emacs.d/Sacha.html and http://www.wisdomandwonder.com/wordpress/wp-content/uploads/2014/03/C3F.html

#+BEGIN_SRC emacs-lisp
(setq savehist-file "~/.emacs.d/savehist")
(savehist-mode 1)
(setq history-length t)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history 1)
(setq savehist-additional-variables
      '(kill-ring
        search-ring
        regexp-search-ring))
#+END_SRC

*** Windowing mode configuration
When running in a graphical mode, I want to hide all the extra cruft that I don't use.

Turn off mouse interface early in startup to avoid momentary display

#+BEGIN_SRC emacs-lisp
(when (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
#+END_SRC

No splash screen please

#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
#+END_SRC

*** Look & Feel (UX)

**** Color scheme
My preference is the Cyberpunk theme, which was pulled from Overtone.

#+BEGIN_SRC emacs-lisp
(load-theme 'cyberpunk t)
#+END_SRC

**** Fonts

#+BEGIN_SRC emacs-lisp
  (when (eq system-type 'darwin)
    (set-face-attribute 'default nil :family "Monaco")
    (set-face-attribute 'default nil :height 200))
#+END_SRC

*** UTF-8 Support

From http://www.wisdomandwonder.com/wordpress/wp-content/uploads/2014/03/C3F.html
#+BEGIN_SRC emacs-lisp
(prefer-coding-system 'utf-8)
(when (display-graphic-p)
  (setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING)))
#+END_SRC
